#Nome do workflow: Pipeline DevOps
name: Pipeline DevOps

#Trigger de execução do workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
#Primeiro Job: Build
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Instalar Dependências
      run: |
        pip install flask
    - name: Teste de Sintaxe
      run: |
        python -m py_compile app.py

#Segundo Job: Deploy
  deploy:
    runs-on: ubuntu-latest
    needs: build 
    steps:
    - name: Simulação de Deploy
      run: |
        echo "Aplicação entregue com sucesso!"