name: Unit Tests

on:
  pull_request:
    branches: [ "main" ]

# Tarefas (jobs) que serão executadas
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install flask
      - name: Run tests
        run: |
          python -m unittest test_app.py
# O comando falhará se algum teste dentro de 'test_app.py' não passar